### ISSUE TITLE
How to merge output and outpput2

### ISSUE THREAD

**Issue by wjzhang-ty** [Barrett-python/DuAT#1]
Thank you very much for sharing the code. I have a small question.

When training the network, S1(output) and S2(output2) are used to calculate the loss  -> L = L(S1, G) + L(S2, G).
When test the network, how to merge S1(output) and S2(output2) to get result?

**Comment by Barrett-python** [comment]
I'm going to choose the way is add method, which is S1(output) + S2(output2).

**Comment by sunshinelike** [comment]
> I'm going to choose the way is add method, which is S1(output) + S2(output2).

how to realize this?
