### ISSUE TITLE
 share more details of the code

### ISSUE THREAD

**Issue by wjzhang-ty** [Barrett-python/DuAT#2]
I have been studying your work, but I can't get the score in the paper.
Can you share more details of the code? I will be very grateful.

**Comment by amadzarak** [comment]
Just to add to the above, I was hoping gain some more clarification on the "Deep Supervision" flow with the output from the GLSA modules, s1, and the SBA module, s2. I have been used `JaccardIndex(task='binary', num_classes=2)` and `BCEWithLogitsLoss()` with some success. But I am interested to understand how you implemented deep supervision.

**Comment by Barrett-python** [comment]
The rest of the code is being collated and will soon be open source.

In the training stage, S1 and S2 output of the model need GT supervision, while in the inference stage, S1 and S2 need to be added together as the final prediction result.

**Comment by Barrett-python** [comment]
I've uploaded all the code.
